[project]
name = "hsr-live-tools"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "regex>=2025.11.3",
    "snownlp>=0.12.3",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
